language: node_js

node_js:
  - 5.9.1

env:
  global:
    - DB_MYSQL_HOST=localhost
    - DB_MYSQL_USER=root 
    - DB_MYSQL_NO_PASSWORD=true
    - DB_MYSQL_DATABASE=j2w1xpr3s01xy8ob

before_install:
  - mysql -e "drop database if exists j2w1xpr3s01xy8ob;" -u root
  - mysql -e "create database j2w1xpr3s01xy8ob;" -u root
  - mysql < src/api/db.sql -u root

before_script:
  - bower install
  - gulp

services:
  - mysql

deploy:
  skip_cleanup: true
  app: still-refuge-85888
  provider: heroku
  api_key:
    secure: bbuEx0PAnV79EEoZAFeR382VZtt6OktGhShRZ3srPv5spNrZLPUp6m+MG65odNJZXhPfE8we2HZ2LXVBrV14AKQFEJAxpuMlNthbxICGrDbBbcTKB7h+paujwsngMMm8JXG/MarhxNnsF1hobeT/0jkefetbA1s4ZOp0S9hNbBTjj0Q9EWfPlVjKevFEzMTT9nae3UmcTCqHK5ZLhwGNb5/0YQCSY6BGpxoAi4Vi+33UpYsK+QN+rnmuk9PGyWCtTQLyUhjyHLu55Z0vxYtaw+qFD+PROJHcrk0JkLyqlNIEwKKdiVxkaDzBfepLxGN0hiVlwYMnQOzMXP5uZcLrLkmRX/Ebs830mWQ5B8x8Cn3hwB6KynrHVfFFtTXtHoKjV1Q/IMAXhmNEvzVK8hvDRR0Wy0GwB57uENOy36QibBpz5i56T0i6jiQWu0CcHAPwQzXsOFv2gTaGyQEyks9lTHOrm5X0DT14Xa6fBbbrOcXYtD6IEYJoVB1EUoKZus0EvkEKevZ0iQZXPTJ0maG8sHz8QNIhAITUbwEfOoF2tdOiDm2J02CKssSLa/yhSLYlY5DPbaoNRqGT1loZL4/uifkOy4D/WhCeJAu6s2aVWwCkuXKYXxppL9QPNu1jFg607ZTZQhTR9TMtVfie59iRd86db2tH7anT0tsMpUQLV+I=
