DROP DATABASE IF EXISTS j2w1xpr3s01xy8ob;

CREATE DATABASE j2w1xpr3s01xy8ob;
 
CREATE TABLE j2w1xpr3s01xy8ob.produtos (
	id BIGINT NULL AUTO_INCREMENT, 
	nome VARCHAR(45) NOT NULL, 
	descricao VARCHAR(255) NOT NULL, 
	preco DOUBLE NOT NULL, 
	PRIMARY KEY (`id`)
);
